# Generated by Django 4.0.2 on 2022-02-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
