# Generated by Django 4.0.2 on 2022-02-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_users', '0003_customuser_education_customuser_maritalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.IntegerField(choices=[(1, 'SCHOOL'), (2, 'COLLEGE'), (3, 'UNIVERSITY')], null=True, verbose_name='Семейное положение'),
        ),
    ]
